### ISSUE TITLE
Error creating push publishing implementation

### ISSUE THREAD

**Issue by ginoliang1130** [WowzaMediaSystems/wse-example-pushpublish-hls#18]
Hi There,

I'm trying to send HLS Stream to local disk. I'm following this guide. It's my config has an unpredictable error?

WowzaStreamingEngine Version: 4.8.0

My sample files:
PushPublishProfilesCustom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Root>
	<PushPublishProfiles>
		<PushPublishProfile>
			<Name>cupertino-file</Name>
			<Protocol>HTTP</Protocol>
			<BaseClass>com.mycompany.wms.example.pushpublish.protocol.cupertino.PushPublishHTTPCupertinoFileHandler</BaseClass>
			<UtilClass></UtilClass>
			<GroupPlaylistClass>com.wowza.wms.pushpublish.groupplaylist.PushPublishGroupPlaylist</GroupPlaylistClass>
			<Implementation>
				<Name>Cupertino File</Name>
			</Implementation>
			<HTTPConfiguration>
			</HTTPConfiguration>
			<Properties>
			</Properties>
		</PushPublishProfile>
		<PushPublishProfile>
			<Name>cupertino-http</Name>
			<Protocol>HTTP</Protocol>
			<BaseClass>com.mycompany.wms.example.pushpublish.protocol.cupertino.PushPublishHTTPCupertinoHTTPHandler</BaseClass>
			<UtilClass></UtilClass>
			<GroupPlaylistClass>com.wowza.wms.pushpublish.groupplaylist.PushPublishGroupPlaylist</GroupPlaylistClass>
			<Implementation>
				<Name>Cupertino HTTP</Name>
			</Implementation>
			<HTTPConfiguration>
			</HTTPConfiguration>
			<Properties>
			</Properties>
		</PushPublishProfile>
	</PushPublishProfiles>
</Root>
```

PushPublishMap.txt
```
ch1_source={"entryName":"ch1_source", "profile":"cupertino-file", "streamName":"ch1_source", "destinationName":"filesystem", "file.root":"/tmp/ch1/", "enabled":"true", "debugLog":"true"}
```

Error Logs:
```
WARN    server  comment 2020-07-31      09:17:00    PushPublishUtils.startSessionForStream[ch1_source] stream:ch1_source[createClass]: Error creating push publishing implementation: com.mycompany.wms.example.pushpublish.protocol.cupertino.PushPublishHTTPCupertinoFileHandler: : java.lang.ClassNotFoundException: com.mycompany.wms.example.pushpublish.protocol.cupertino.PushPublishHTTPCupertinoFileHandler|at java.base/java.net.URLClassLoader.findClass(Unknown Source)|at java.base/java.lang.ClassLoader.loadClass(Unknown Source)|at java.base/java.lang.ClassLoader.loadClass(Unknown Source)|at java.base/java.lang.Class.forName0(Native Method)|at java.base/java.lang.Class.forName(Unknown Source)
```

**Comment by ginoliang1130** [comment]
wowza support request, # (365524)

**Comment by akeller** [comment]
Thank you for submitting a support request. Please continue following up there for assistance.
